kind: template
load: nodeProject.jsonnet
data:
  node: 22
  port: ''
  deployToHost: 192.168.178.2
  environmentVariables: '["NGINX_PROXY_MANAGER_CERT_ID", "AWS_CERTIFICATE", "AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY"]'
  parameters: '-v /mnt/data/nginx-proxy-manager:/nginx-proxy-manager'
  dockerName: 'npm-cert-sync-aws-dasred.de'